[package]
name = "iggy_wasm_server"
version = "0.0.1"
license = "Unlicense"
description = "Sample data streamer embeddable via a WASI component"

[dependencies]
hyperliquid_rust_sdk = "0.5.0"
iggy = "0.6.203"
